### ISSUE TITLE
Several documented options cause "unrecognized arguments" errors

### ISSUE THREAD

**Issue by twosigmajab** [twosigma/marbles#110]
* marbles.core version: 0.10.0
* marbles.mixins version: 0.10.0
* Python version: 3.6+
* Operating System: N/A

### Description

Several of marbles' documented options cause "unrecognized arguments" errors when I try to use them.

### What I Did

```
$ python3 -m marbles -h | grep TOP
  -t TOP, --top-level-directory TOP

$ python3 -m marbles -t tests
python3 -m marbles: error: unrecognized arguments: -t

$ python3 -m marbles --top-level-directory tests
python3 -m marbles: error: unrecognized arguments: --top-level-directory

$ python3 -m marbles -h | grep START
  -s START, --start-directory START

$ python3 -m marbles -s tests
python3 -m marbles: error: unrecognized arguments: -s

$ python3 -m marbles --start-directory tests
python3 -m marbles: error: unrecognized arguments: --start-directory
```

### Expected behavior
The options work as promised.

**Comment by twosigmajab** [comment]
Looks like if I add "discover" after "-m marbles", it works:
```
$ python3 -m marbles discover --start-directory tests
...
----------------------------------------------------------------------
Ran 4 tests in 0.866s

OK
```

**Comment by leifwalsh** [comment]
As far as I can tell, this is the same behavior as `python -m unittest`, which is what we intend. I think this should be “works as designed”, what do you think?

**Comment by twosigmajab** [comment]
Now that I look more closely at the help output, and notice that it's just concatenating onto the usage for the toplevel command the usage for the `discover` subcommand`, I realize that this *is* working as designed, and am closing. But not without noting that this design seems unusual and error-prone (cf. this issue). unittest's top-level help output should only mention that `discover` is a subcommand that you can run `unittest discover -h` to get the usage for, rather than munging them together. This is how the help output for CLIs with subcommands implemented with Click work, and seems more common, composable, and user-friendly (imagine if e.g. `git -h` worked like `unittest -h`). If I get time to open an upstream bug for this I'll link to it from here. Thanks for the quick response!
