### ISSUE TITLE
Fix the broken Travis CI link and Issue Template link on the Contributing page

### ISSUE THREAD

**Issue by joshhn** [twosigma/marbles#143]
### Description
- [Travis CI link](https://travis-ci.org/twosigma/marbles/pull_requests) in step 3 of `Pull Request Guidelines` is broken.
- In the `Report Bugs` part of the `Types of Contributions` section, the `issue template` link is better to link to [this one
](https://github.com/twosigma/marbles/issues/new/choose)

### Intended audience
Developers,  maintainers.

### Additional context
The improvement makes the contributors' experience better for creating issues with templates available and checking if tests pass for all supported Python versions.

**Comment by leifwalsh** [comment]
I should really finish up and land #136. I'll try to fold these changes in to that.
