### ISSUE TITLE
Add a distutils command for marbles

### ISSUE THREAD

**Issue by leifwalsh** [twosigma/marbles#50]
**Is your feature request related to a problem? Please describe.**

It would be good to enable people to run `python setup.py marbles` and get the effect of switching from `python -m unittest` to `python -m marbles`, and also to alias `test` to `marbles`.

**Describe the solution you'd like**

Marbles should provide a `setuptools.Command` subclass and install it as an additional [setuptools command](http://setuptools.readthedocs.io/en/latest/setuptools.html#adding-commands)

A blog post describes this in more detail [here](https://dankeder.com/posts/adding-custom-commands-to-setup-py/).

Marbles should also document how to integrate this with a project, by adding `marbles` as a `setup_requires` and `tests_require` dependency, and adding the following to `setup.cfg`:

```
[aliases]
test = marbles
```

**Comment by wyegelwel** [comment]
For those following along at home, I've made some progress:

```
 python setup.py marbles
running marbles

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

Now I need to figure out how to get marbles to actually find the tests in the directory...

**Comment by leifwalsh** [comment]
Discussed in person.  Looks like `setuptools` isn't using `unittest`'s discovery mechanism either, it has its own thing: https://github.com/pypa/setuptools/blob/master/setuptools/command/test.py#L230

For compatibility, we should probably subclass this thing and override the places where it invokes `unittest` to actually run the test, and replace them with `marbles`.
