### ISSUE TITLE
Upgrade Pandas version to latest version >=0.23.1

### ISSUE THREAD

**Issue by dirkesquire** [twosigma/marbles#80]
I love marbles! I also enjoyed Jane's talk at PyData Amsterdam.

My issue is that installing marbles automatically downgrades your pandas version.

If you do: `pip install pandas` it installs version 0.23.1 at the time of writing.
Then running `pip install marbles` downgrades pandas to 0.21.

This causes the following code to break:

```
from datetime import datetime
import pandas as pd

data = {
            datetime(2018,4,1): [2500, 1500],
            datetime(2018,5,1): [2000, 2500],
            datetime(2018,6,1): [2000, 1500],
    }
df = pd.DataFrame.from_dict(data, orient='index', columns = ['Income', 'Expense'])
print(df)
```

I believe the line is on marbles/marbles/mixins/setup.py line 57. 

I could try and do a pull request if you wanted, but I'm not sure what all tests I would need to ensure are passing?

**Comment by leifwalsh** [comment]
Yep, this is something we should do. @thejunglejane what kind of testing do you want to do about it?

**Comment by thejunglejane** [comment]
We're currently using *very little* of the pandas API: we turn a sequence of date(time)s into a series and then shift the series. See [assertDateTimesFrequencyEqual](https://github.com/twosigma/marbles/blob/be166fedc2f7253949f13ca624ee661c7a2df49b/marbles/mixins/marbles/mixins/mixins.py#L1496-L1497) if you're curious.

I can review the pandas changelog and run our normal suite of tests with 0.22 and 0.23 and I think that'll be enough.
